/* AUTOGENERATED - DO NOT EDIT BY HAND */

  export const singleLineCharts = {
  "1047: Number of Xbox Live MAU Q1 2016 - Q4 2019 (12)": "manifests/autogen/line-single/line-single-manifest-1047.json",
  "1066: Median age of the population in Vietnam 2015 (13)": "manifests/autogen/line-single/line-single-manifest-1066.json",
  "1107: Unemployment rate in Spain 2005 to 2019 (14)": "manifests/autogen/line-single/line-single-manifest-1107.json",
  "128: Cattle population worldwide 2012 to 2019 (15)": "manifests/autogen/line-single/line-single-manifest-128.json",
  "172: Median household income in the United States 1990 to 2018 (16)": "manifests/autogen/line-single/line-single-manifest-172.json",
  "328: General Motors - number of employees 2019 (17)": "manifests/autogen/line-single/line-single-manifest-328.json",
  "375: Tesla's revenue 2008 to 2019 (18)": "manifests/autogen/line-single/line-single-manifest-375.json",
  "489: Growth rate of the global cosmetics market 2004 to 2018 (19)": "manifests/autogen/line-single/line-single-manifest-489.json",
  "508: Indonesia: number of internet users 2017 to 2023 (20)": "manifests/autogen/line-single/line-single-manifest-508.json",
  "541: USA - number of arrests for all offenses 1990 to 2018 (21)": "manifests/autogen/line-single/line-single-manifest-541.json",
  "595: Number of births in Canada 2000 to 2019 (22)": "manifests/autogen/line-single/line-single-manifest-595.json",
  "605: Samsung Electronics' operating profit 2009-2019, by quarter (23)": "manifests/autogen/line-single/line-single-manifest-605.json",
  "7: Estimated number of World of Warcraft subscribers 2015 to 2023 (24)": "manifests/autogen/line-single/line-single-manifest-7.json",
  "746: Inflation rate in Sri Lanka 2024 (25)": "manifests/autogen/line-single/line-single-manifest-746.json",
  "843: New York Yankees revenue 2001 to 2018 (26)": "manifests/autogen/line-single/line-single-manifest-843.json",
  "881: FedEx's revenue 2009 to 2019 (27)": "manifests/autogen/line-single/line-single-manifest-881.json",
  "887: Youth unemployment rate in India in 2019 (28)": "manifests/autogen/line-single/line-single-manifest-887.json",
  "913: Number of commercial casinos in the U.S. 2005 to 2018 (29)": "manifests/autogen/line-single/line-single-manifest-913.json",
  "930: Suicide rate in Japan 2009 to 2018 (30)": "manifests/autogen/line-single/line-single-manifest-930.json",
  "937: Movie releases in North America from 2000 to 2019 (31)": "manifests/autogen/line-single/line-single-manifest-937.json",
  "951: National debt of Ireland 2024 (32)": "manifests/autogen/line-single/line-single-manifest-951.json",
  "965: Annual performance of the Dow Jones Composite Index 2000 to 2019 (33)": "manifests/autogen/line-single/line-single-manifest-965.json",
  "979: Total number of gang-related homicides in the United States 2012 (34)": "manifests/autogen/line-single/line-single-manifest-979.json",
  "Charizard: Holographic Charizard Card Price (35)": "manifests/autogen/line-single/line-single-manifest-Charizard.json"
};
  
  export const multiLineCharts = {
  "128: Gross domestic product (GDP) growth in EU and Euro area 2024 (2)": "manifests/autogen/line-multi/line-multi-manifest-128.json",
  "16: Distribution of the workforce across economic sectors in India 2019 (3)": "manifests/autogen/line-multi/line-multi-manifest-16.json",
  "175: Distribution of gross domestic product (GDP) across economic sectors Pakistan 2018 (4)": "manifests/autogen/line-multi/line-multi-manifest-175.json",
  "233: Advertising spending in Vietnam 2004-2018, by medium (5)": "manifests/autogen/line-multi/line-multi-manifest-233.json",
  "261: Passenger cars - sales in selected countries worldwide 2005 to 2018 (6)": "manifests/autogen/line-multi/line-multi-manifest-261.json",
  "27: Adidas, Nike & Puma revenue comparison 2006 to 2018 (7)": "manifests/autogen/line-multi/line-multi-manifest-27.json",
  "57: Distribution of GDP across economic sectors in China 2008 to 2018 (8)": "manifests/autogen/line-multi/line-multi-manifest-57.json",
  "67: Gross domestic product of the BRIC countries from 2014 to 2024 (9)": "manifests/autogen/line-multi/line-multi-manifest-67.json",
  "76: Inflation rate in EU and Euro area 2024 (10)": "manifests/autogen/line-multi/line-multi-manifest-76.json",
  "Pokemon: Holographic Pokemon Card Price (11)": "manifests/autogen/line-multi/line-multi-manifest-Pokemon.json"
};
  
  export const singleBarCharts = {
  "1018: Unemployment rate in Greece 1999-2019 (1)": "manifests/autogen/bar-single/bar-single-manifest-1018.json"
};
  
  export const multiBarCharts = {
  "48: Gross domestic product of the ASEAN countries from 2008 to 2018 (0)": "manifests/autogen/bar-multi/bar-multi-manifest-48.json"
};
  
  export const scatterCharts = {
  "d3 (42)": "manifests/scatter-manifest-d3.json",
  "Old Faithful Geyser Eruptions (44)": "manifests/scatter-manifest-geyser.json",
  "Iris Flower Data Set (47)": "manifests/scatter-manifest-iris-petal.json",
  "s1 (49)": "manifests/scatter-manifest-s1.json",
  "s2 (51)": "manifests/scatter-manifest-s2.json"
};
  
  export const pastryCharts = {
  "Division of energy in the Universe (40)": "manifests/pie-manifest-dark-matter.json"
};
  