
import argparse
import json
import pprint
import sys
from pathlib import Path

class Group(dict):
    pass

import_jsons = []

no_edit = """
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/
"""

def main(args):
    p = Path(args.dir)
    tree = {}
    load_dir(Path(args.dir), tree, None)
    missing_descriptions = find_missing_descriptions(tree, tree)
    if missing_descriptions:
        print('Config settings without descriptions:', file=sys.stderr)
        for setting_path in missing_descriptions:
            print(f'  {setting_path}', file=sys.stderr)
        raise ValueError('All visible config settings must have descriptions')
    # pprint.pp(tree)
    with open(p / 'config_types.ts', 'w') as typesf, \
        open(p / 'config_defaults.ts', 'w') as defaultsf, \
        open(p / 'config_metadata.ts', 'w') as metadataf:
        print(no_edit, file=defaultsf)
        print('import { Config } from \'./config_types\';', file=defaultsf)
        print('export const defaultConfig: Config = {', file=defaultsf)
        write_defaults_group('', tree, tree, defaultsf, indent = 2)
        print('}', file=defaultsf)

        print(no_edit, file=typesf)
        print(
"""
import { type ChartType, type Size2d } from '@fizz/chartsignal-internal';
import { type SnapLocation } from '../common/types';
import { type Color } from '../common/color_types';

/**
 * A single config item.
 * @public
 */
export type ConfigSetting = string | number | boolean;
/**
 * A group of config settings (which may contain nested config groups).
 * @public
 */
export type ConfigGroup = {[key: string]: ConfigSetting | ConfigGroup | undefined};
/**
 * A mapping of dotted setting paths to values.
 * @public
 */
export type SettingsInput = {[path: string]: ConfigSetting};

/** SVG viewBox dimensions for chart viewport
 * @public
 */
export interface ViewBox extends ConfigGroup {
  /** X coordinate of top-left corner */
  x: number;
  /** Y coordinate of top-left corner */
  y: number;
  /** Width of viewable area */
  width: number;
  /** Height of viewable area */
  height: number;
}

/** @public */
export type VertDirection = 'up' | 'down';

/** @public */
export type HorizDirection = 'left' | 'right';

/** @public */
export type PlaneDirection = VertDirection | HorizDirection;

/** @public */
export type DepthDirection = 'in' | 'out';

/** @public */
export type Direction = VertDirection | HorizDirection | DepthDirection;

/** @public */
export const directions: Direction[] = ['up', 'down', 'left', 'right', 'in', 'out'];

/** @public */
export type VertCardinalDirection = 'north' | 'south';
/** @public */
export type HorizCardinalDirection = 'east' | 'west';

/**
 * Which direction is "up" on a chart.
 * @public
 */
export type CardinalDirection = VertCardinalDirection | HorizCardinalDirection;
/** Order for legend items
 * @public
 */
export type LegendItemOrder = 'alphabetical' | 'reverseAlphabetical' | 'startingOrder' | 'endingOrder';

/** Position for data value labels on bars
 * @public
 */
export type BarDataLabelPosition = 'center' | 'end' | 'base' | 'outside';
/** Format for label display - 'raw' for unformatted or format string
 * @public
 */
export type LabelFormat = 'raw' | string;
/** Control panel tab label display style
 * @public
 */
export type TabLabelStyle = 'icon' | 'iconLabel' | 'label';
/** Which axis to animate along during chart reveal
 * @public
 */
export type AnimationType = 'yAxis' | 'xAxis' | 'none';

/** Starting point for chart animations
 * @public
 */
export type AnimationOrigin = 'baseline' | 'top' | 'initialValue' | 'custom';
/**
 * Identifies the source that set a color preference value.
 * Determines whether an incoming change (e.g. from a mode or system event)
 * is allowed to override the current value.
 * @public
 */
export type ColorPrefSource =
  | 'default'      // ParaCharts fallback
  | 'chartDefault' // author/manifest default
  | 'modeDefault'  // set by an active mode (e.g. low-vision mode)
  | 'profile'      // saved in manifest extensions
  | 'system'       // derived from current media-query state
  | 'user';        // explicit user choice — wins until explicitly reset

/** @public */
export type DeepReadonly<T> = {
  readonly [Property in keyof T]: T extends ConfigSetting ? T[Property] : DeepReadonly<T[Property]>;
};
""", file=typesf)
        write_types_group([], tree, tree, typesf)

        print(no_edit, file=metadataf)
        write_metadata_header(p, [], tree, tree, metadataf)
        print(
"""
import { type ConfigGroupMetadata, type ConfigMetadata } from './config_metadata_types';
export type * from './config_metadata_types';
""", file=metadataf)
        print('export const configMetadata: ConfigMetadata = {', file=metadataf)
        write_metadata_group([''], tree, tree, metadataf)
        print('}', file=metadataf)
        print(
"""
for (const [k, v] of Object.entries(configMetadata)) {
  if (!v) continue;
  if (v.ref) {
    const refTarget = configMetadata[v.ref];
    if (!refTarget) throw new Error(`Unknown config metadata ref: ${v.ref}`);
    const resolvedGroup = Object.assign(Object.create(refTarget), v) as ConfigGroupMetadata;
    resolvedGroup.settings = Object.assign(Object.create(refTarget.settings), v.settings);
    configMetadata[k] = resolvedGroup;
    for (const [sk, sv] of Object.entries(resolvedGroup.settings)) {
      const inheritedSetting = refTarget.settings[sk];
      if (inheritedSetting) {
        resolvedGroup.settings[sk] = Object.assign(Object.create(inheritedSetting), sv);
      }
    }
  }
}
""".rstrip(), file=metadataf)


def load_dir(dir: Path, node, parent):
    print(f'read dir {dir}')

    for kid in sorted(dir.iterdir(), key=lambda path: path.name):
        if kid.is_dir():
            node[kid.stem] = Group()
            load_dir(kid, node[kid.stem], node)
        elif kid.suffix == '.json':
            if kid.stem == 'index':
                load_file(kid, node, parent)
            else:
                node[kid.stem] = Group()
                load_file(kid, node[kid.stem], node)


def load_file(file: Path, node, parent):
    print(f'read file {file}')
    with open(file) as f:
        md = json.load(f)
    if md.get('description'):
        node['__description__'] = md['description']
    if md.get('ref'):
        node['__ref__'] = md['ref']
    if md.get('abstract'):
        node['__abstract__'] = md['abstract']
    if not md.get('settings'):
        return
    for k, v in md['settings'].items():
        node[k] = v


def write_defaults_group(key, node, tree, defaults, indent = 0):
    if node.get('__abstract__'):
        return
    if key:
        print(f'{" "*indent}{key}: {{', file=defaults)

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        new_node = tree
        for part in parts:
            new_node = new_node[part]
        new_node = new_node.copy()
        new_node.update(node)
        del new_node['__ref__']
        node = new_node
        if node.get('__abstract__'):
            del node['__abstract__']
    for k, v in node.items():
        if k.startswith('__'):
            continue
        if isinstance(v, Group):
            write_defaults_group(k, v, tree, defaults, indent = indent + 2)
        else:
            write_defaults_item(k, v, defaults, indent = indent + 2)

    if key:
        print(f'{" "*indent}}},', file=defaults)

def write_defaults_item(key, setting, defaults, indent = 0):
    print(f'{" "*indent}{key}: {js_value(setting.get('default'))},', file=defaults)

def js_value(py_val):
    if isinstance(py_val, bool):
        return 'true' if py_val else 'false'
    elif isinstance(py_val, str):
        return f'"{py_val}"'
    elif py_val is None:
        return 'null'
    else:
        return str(py_val)


def write_types_group(key_path, node, tree, types):
    print('write types group', '.'.join(key_path))
    key_path_joined = ''.join([k.capitalize() for k in key_path])

    resolved_node = resolve_group(node, tree)
    description = resolved_node.get('__description__', 'Complete ParaCharts configuration tree.')
    print('/**', file=types)
    print(f' * {description}', file=types)
    print(' * @public', file=types)
    print(' */', file=types)
    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        print('parts', parts)
        parts_joined = ''.join([p.capitalize() for p in parts])
        iface = parts_joined + 'Config'
        print(f'export interface {key_path_joined}Config extends {iface} {{', file=types)
        # print('}', file=types)

        # new_node = tree
        # for part in parts:
        #     new_node = new_node[part]
        # new_node = new_node.copy()
        # if new_node.get('__abstract__'):
        #     del new_node['__abstract__']
        # for k, v in new_node.items():
        #     if not isinstance(v, Group):
        #         v.update(node[k])
        # #new_node.update(node)
        # #del new_node['__ref__']
        # node = new_node
    else:
        print(f'export interface {key_path_joined}Config extends ConfigGroup {{', file=types)

    groups = []
    items = []
    for k, v in node.items():
        if isinstance(v, Group):
            groups.append([k, v])
        else:
            items.append([k, v])
    for k, v in items:
        if not isinstance(v, dict):
            continue
        if not v.get('description'):
            continue
        write_types_item(k, v, types)
    for k, v in groups:
        if v.get('__abstract__'):
            continue
        group_description = resolve_group(v, tree).get('__description__')
        if group_description:
            print(f'  /** {group_description} */', file=types)
        print(f'  {k}: {key_path_joined + k.capitalize()}Config;', file=types)
    print('}', file=types)

    for k, v in groups:
        write_types_group(key_path + [k], v, tree, types)


def resolve_group(node, tree):
    resolved = Group()
    if node.get('__ref__'):
        ref_node = tree
        for part in node['__ref__'].split('.'):
            ref_node = ref_node[part]
        resolved.update(resolve_group(ref_node, tree))
        resolved.pop('__abstract__', None)

    for key, value in node.items():
        if key == '__ref__':
            continue
        if isinstance(value, dict) and not isinstance(value, Group) and isinstance(resolved.get(key), dict):
            merged_setting = resolved[key].copy()
            merged_setting.update(value)
            resolved[key] = merged_setting
        else:
            resolved[key] = value
    return resolved


def find_missing_descriptions(node, tree, path = []):
    resolved = resolve_group(node, tree)
    if resolved.get('__abstract__'):
        return []

    missing = []
    for key, value in resolved.items():
        if key.startswith('__'):
            continue
        setting_path = path + [key]
        if isinstance(value, Group):
            missing.extend(find_missing_descriptions(value, tree, setting_path))
        elif isinstance(value, dict) and not value.get('description'):
            missing.append('.'.join(setting_path))
    return missing

def write_types_item(key, setting, types):
    print(f'  /** {setting.get('description')} */', file=types)
    print(f'  {key}: {setting.get('type')};', file=types)


def write_metadata_header(dir_path, key_path, node, tree, f):
    print('write metadata header', '/'.join(key_path))
    key_path_file = '/'.join(key_path) + '.json'
    key_path_dir = '/'.join(key_path) + '/index.json'
    key_path_joined = ''.join([k.capitalize() for k in key_path])
    if key_path_joined:
        import_json = key_path_joined + 'Json'
        if (dir_path / key_path_file).exists():
            print(f'import {import_json} from "./{key_path_file}" with {{ type: "json" }};', file=f)
        elif (dir_path / key_path_dir).exists():
            print(f'import {import_json} from "./{key_path_dir}" with {{ type: "json" }};', file=f)
        else:
            import_json = ''
        if import_json:
            import_jsons.append(import_json)

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        new_node = tree
        for part in parts:
            new_node = new_node[part]
        new_node = new_node.copy()
        for k, v in new_node.items():
            if k.startswith('__'):
                continue
            if not isinstance(v, Group) and node.get(k):
                v.update(node[k])
        node = new_node
    groups = []
    items = []
    for k, v in node.items():
        if isinstance(v, Group):
            groups.append([k, v])
        else:
            items.append([k, v])
    # for k, v in items:
    #     process_types_item(k, v, types)
    # for k, v in groups:
    #     print(f'  {k}: {key_path_joined + k.capitalize()}Config;', file=types)
    # print('}', file=types)

    for k, v in groups:
        write_metadata_header(dir_path, key_path + [k], v, tree, f)


def write_metadata_group(key_path, node, tree, f):
    # 'sonification': SonificationJson,
    # print('write metadata group', '.'.join(key_path))
    key_path_joined = ''.join([k.capitalize() for k in key_path])
    key_path_dotted = '.'.join(key_path[1:])
    if key_path_joined:
        import_json = key_path_joined + 'Json'
        if import_json in import_jsons:
            print(f'  \'{key_path_dotted}\': {import_json} as unknown as ConfigGroupMetadata,', file=f)

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        new_node = tree
        for part in parts:
            new_node = new_node[part]
        new_node = new_node.copy()
        for k, v in new_node.items():
            if k.startswith('__'):
                continue
            if not isinstance(v, Group) and node.get(k):
                v.update(node[k])
        node = new_node
    groups = []
    items = []
    for k, v in node.items():
        if isinstance(v, Group):
            groups.append([k, v])
        else:
            items.append([k, v])

    for k, v in groups:
        write_metadata_group(key_path + [k], v, tree, f)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('dir',
                        help='Directory containing config metadata files')
    # parser.add_argument('charts', nargs='*',
    #                     help='list of charts to include')
    # parser.add_argument('-r', '--range', default='',
    #                     help='range of lines to extract (as `start-end`)')
    # parser.add_argument('-o', '--outfile', default='filelist.json',
    #                     help='output filename')
    args = parser.parse_args()
    main(args)
