
import argparse
import json
import pprint
from pathlib import Path

class Group(dict):
    pass

import_jsons = []

no_edit = """
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/
"""

def main(args):
    p = Path(args.dir)
    tree = {}
    load_dir(Path(args.dir), tree, None)
    # pprint.pp(tree)
    with open(p / 'config_types.ts', 'w') as typesf, \
        open(p / 'config_defaults.ts', 'w') as defaultsf, \
        open(p / 'config_metadata.ts', 'w') as metadataf:
        print(no_edit, file=defaultsf)
        print('import { Config } from \'./config_types\';', file=defaultsf)
        print('export const defaultConfig: Config = {', file=defaultsf)
        write_defaults_group('', tree, tree, defaultsf, indent = 2)
        print('}', file=defaultsf)

        print(no_edit, file=typesf)
        print(
"""
import { type Size2d } from '@fizz/chart-classifier-utils'
import { type SnapLocation } from '../common/types';
import { type Color } from '../common/color_types';

/**
 * A single config item.
 * @public
 */
export type ConfigSetting = string | number | boolean;
/**
 * A group of config settings (which may contain nested config groups).
 * @public
 */
export type ConfigGroup = {[key: string]: ConfigSetting | ConfigGroup | undefined};

/** Chart types that display individual points
 * @public
 */
export type PointChartType = 'line' | 'stepline' | 'scatter';

/** Chart types drawn using a Cartesian coordinate system
 * @public
 */
export type PlaneChartType = 'bar' | 'lollipop' | PointChartType;

/** Chart types that use radial/circular layout
 * @public
 */
export type PastryChartType = 'pie' | 'donut' | 'gauge';

/** All supported chart types
 * @public
 */
export type ChartType = PlaneChartType | PastryChartType;

/** @public */
export type VertDirection = 'up' | 'down';

/** @public */
export type HorizDirection = 'left' | 'right';

/** @public */
export type PlaneDirection = VertDirection | HorizDirection;

/** @public */
export type DepthDirection = 'in' | 'out';

/** @public */
export type Direction = VertDirection | HorizDirection | DepthDirection;

/** @public */
export const directions: Direction[] = ['up', 'down', 'left', 'right', 'in', 'out'];

/** @public */
export type VertCardinalDirection = 'north' | 'south';
/** @public */
export type HorizCardinalDirection = 'east' | 'west';

/**
 * Which direction is "up" on a chart.
 * @public
 */
export type CardinalDirection = VertCardinalDirection | HorizCardinalDirection;
/** Order for legend items
 * @public
 */
export type LegendItemOrder = 'alphabetical' | 'reverseAlphabetical' | 'startingOrder' | 'endingOrder';

/** Position for data value labels on bars
 * @public
 */
export type BarDataLabelPosition = 'center' | 'end' | 'base' | 'outside';
/** Format for label display - 'raw' for unformatted or format string
 * @public
 */
export type LabelFormat = 'raw' | string;
/** Control panel tab label display style
 * @public
 */
export type TabLabelStyle = 'icon' | 'iconLabel' | 'label';
/** Which axis to animate along during chart reveal
 * @public
 */
export type AnimationType = 'yAxis' | 'xAxis' | 'none';

/** Starting point for chart animations
 * @public
 */
export type AnimationOrigin = 'baseline' | 'top' | 'initialValue' | 'custom';

""", file=typesf)
        write_types_group([], tree, tree, typesf)

        print(no_edit, file=metadataf)
        write_metadata_header(p, [], tree, tree, metadataf)
        print(
"""
import { SettingControlType } from '../components';
import { SettingControlOptionsType, RefreshTarget } from '../state';

export interface ConfigSettingMetadata<T extends SettingControlType = SettingControlType> {
  /** Label displayed in UI */
  label?: string;
  /** Internal description of item */
  description?: string;
  /** Stringified Typescript type of item */
  type?: string;
  default: any;
  control: T;
  /** Control-specific options. */
  controlOptions?: SettingControlOptionsType<T>;
  /** Whether item is advanced */
  advanced?: boolean;
  panel?: string;
  parentView?: string;
  hidden?: boolean;
  keywords?: string[];
  /** What to refresh when the setting changes **/
  refresh: RefreshTarget;
}
export interface ConfigGroupMetadata {
  ref?: string;
  settings: ConfigGroupSettingsMetadata;
}
export interface ConfigGroupSettingsMetadata {
  [settingName: string]: ConfigSettingMetadata;
}
export interface ConfigMetadata {
  [groupPath: string]: ConfigGroupMetadata;
}
""", file=metadataf)
        print('export const configMetadata: ConfigMetadata = {', file=metadataf)
        write_metadata_group([''], tree, tree, metadataf)
        print('}', file=metadataf)
        print(
"""
for (const [k, v] of Object.entries(configMetadata)) {
  if (v.ref) {
    const refTarget = configMetadata[v.ref];
    configMetadata[k] = Object.create(refTarget);
    Object.assign(configMetadata[k], v);
    configMetadata[k].settings = Object.create(refTarget.settings);
    Object.assign(configMetadata[k].settings, v.settings);
    for (const [sk, sv] of Object.entries(configMetadata[k].settings!)) {
      if (refTarget.settings![sk]) {
        configMetadata[k].settings![sk] = Object.create(refTarget.settings![sk]);
        Object.assign(configMetadata[k].settings![sk], sv);
      }
    }
  }
}
""", file=metadataf)


def load_dir(dir: Path, node, parent):
    print(f'read dir {dir}')

    for kid in dir.iterdir():
        if kid.is_dir():
            node[kid.stem] = Group()
            load_dir(kid, node[kid.stem], node)
        elif kid.suffix == '.json':
            if kid.stem == 'index':
                load_file(kid, node, parent)
            else:
                node[kid.stem] = Group()
                load_file(kid, node[kid.stem], node)


def load_file(file: Path, node, parent):
    print(f'read file {file}')
    with open(file) as f:
        md = json.load(f)
    if md.get('ref'):
        node['__ref__'] = md['ref']
    if md.get('abstract'):
        node['__abstract__'] = md['abstract']
    if not md.get('settings'):
        return
    for k, v in md['settings'].items():
        node[k] = v


def write_defaults_group(key, node, tree, defaults, indent = 0):
    if node.get('__abstract__'):
        return
    if key:
        print(f'{" "*indent}{key}: {{', file=defaults)

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        new_node = tree
        for part in parts:
            new_node = new_node[part]
        new_node = new_node.copy()
        new_node.update(node)
        del new_node['__ref__']
        node = new_node
        if node.get('__abstract__'):
            del node['__abstract__']
    for k, v in node.items():
        if isinstance(v, Group):
            write_defaults_group(k, v, tree, defaults, indent = indent + 2)
        else:
            write_defaults_item(k, v, defaults, indent = indent + 2)

    if key:
        print(f'{" "*indent}}},', file=defaults)

def write_defaults_item(key, setting, defaults, indent = 0):
    print(f'{" "*indent}{key}: {js_value(setting.get('default'))},', file=defaults)

def js_value(py_val):
    if isinstance(py_val, bool):
        return 'true' if py_val else 'false'
    elif isinstance(py_val, str):
        return f'"{py_val}"'
    elif py_val is None:
        return 'null'
    else:
        return str(py_val)


def write_types_group(key_path, node, tree, types):
    print('write types group', '.'.join(key_path))
    key_path_joined = ''.join([k.capitalize() for k in key_path])

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        print('parts', parts)
        parts_joined = ''.join([p.capitalize() for p in parts])
        iface = parts_joined + 'Config'
        print(f'export interface {key_path_joined}Config extends {iface} {{', file=types)
        # print('}', file=types)

        # new_node = tree
        # for part in parts:
        #     new_node = new_node[part]
        # new_node = new_node.copy()
        # if new_node.get('__abstract__'):
        #     del new_node['__abstract__']
        # for k, v in new_node.items():
        #     if not isinstance(v, Group):
        #         v.update(node[k])
        # #new_node.update(node)
        # #del new_node['__ref__']
        # node = new_node
    else:
        print(f'export interface {key_path_joined}Config extends ConfigGroup {{', file=types)

    groups = []
    items = []
    for k, v in node.items():
        if isinstance(v, Group):
            groups.append([k, v])
        else:
            items.append([k, v])
    for k, v in items:
        if not isinstance(v, dict):
            continue
        if not v.get('description'):
            continue
        write_types_item(k, v, types)
    for k, v in groups:
        if v.get('__abstract__'):
            continue
        print(f'  {k}: {key_path_joined + k.capitalize()}Config;', file=types)
    print('}', file=types)

    for k, v in groups:
        write_types_group(key_path + [k], v, tree, types)

def write_types_item(key, setting, types):
    print(f'  /** {setting.get('description')} */', file=types)
    print(f'  {key}: {setting.get('type')};', file=types)


def write_metadata_header(dir_path, key_path, node, tree, f):
    print('write metadata header', '/'.join(key_path))
    key_path_file = '/'.join(key_path) + '.json'
    key_path_dir = '/'.join(key_path) + '/index.json'
    key_path_joined = ''.join([k.capitalize() for k in key_path])
    if key_path_joined:
        import_json = key_path_joined + 'Json'
        if (dir_path / key_path_file).exists():
            print(f'import {import_json} from "./{key_path_file}" with {{ type: "json" }};', file=f)
        elif (dir_path / key_path_dir).exists():
            print(f'import {import_json} from "./{key_path_dir}" with {{ type: "json" }};', file=f)
        else:
            import_json = ''
        if import_json:
            import_jsons.append(import_json)

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        new_node = tree
        for part in parts:
            new_node = new_node[part]
        new_node = new_node.copy()
        for k, v in new_node.items():
            if k == '__abstract__':
                continue
            if k == '__ref__':
                continue
            if not isinstance(v, Group) and node.get(k):
                v.update(node[k])
        node = new_node
    groups = []
    items = []
    for k, v in node.items():
        if isinstance(v, Group):
            groups.append([k, v])
        else:
            items.append([k, v])
    # for k, v in items:
    #     process_types_item(k, v, types)
    # for k, v in groups:
    #     print(f'  {k}: {key_path_joined + k.capitalize()}Config;', file=types)
    # print('}', file=types)

    for k, v in groups:
        write_metadata_header(dir_path, key_path + [k], v, tree, f)


def write_metadata_group(key_path, node, tree, f):
    # 'sonification': SonificationJson,
    # print('write metadata group', '.'.join(key_path))
    key_path_joined = ''.join([k.capitalize() for k in key_path])
    key_path_dotted = '.'.join(key_path[1:])
    if key_path_joined:
        import_json = key_path_joined + 'Json'
        if import_json in import_jsons:
            print(f'  \'{key_path_dotted}\': {import_json} as unknown as ConfigGroupMetadata,', file=f)

    if node.get('__ref__'):
        parts = node['__ref__'].split('.')
        new_node = tree
        for part in parts:
            new_node = new_node[part]
        new_node = new_node.copy()
        for k, v in new_node.items():
            if k == '__abstract__':
                continue
            if k == '__ref__':
                continue
            if not isinstance(v, Group) and node.get(k):
                v.update(node[k])
        node = new_node
    groups = []
    items = []
    for k, v in node.items():
        if isinstance(v, Group):
            groups.append([k, v])
        else:
            items.append([k, v])

    for k, v in groups:
        write_metadata_group(key_path + [k], v, tree, f)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('dir',
                        help='Directory containing config metadata files')
    # parser.add_argument('charts', nargs='*',
    #                     help='list of charts to include')
    # parser.add_argument('-r', '--range', default='',
    #                     help='range of lines to extract (as `start-end`)')
    # parser.add_argument('-o', '--outfile', default='filelist.json',
    #                     help='output filename')
    args = parser.parse_args()
    main(args)
