
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/

import AnimationJson from "./animation.json" with { type: "json" };
import AxisJson from "./axis/index.json" with { type: "json" };
import AxisHorizJson from "./axis/horiz/index.json" with { type: "json" };
import AxisHorizLineJson from "./axis/horiz/line.json" with { type: "json" };
import AxisHorizTicksJson from "./axis/horiz/ticks/index.json" with { type: "json" };
import AxisHorizTicksLabelsJson from "./axis/horiz/ticks/labels.json" with { type: "json" };
import AxisHorizTitleJson from "./axis/horiz/title.json" with { type: "json" };
import AxisVertJson from "./axis/vert/index.json" with { type: "json" };
import AxisVertLineJson from "./axis/vert/line.json" with { type: "json" };
import AxisVertTicksJson from "./axis/vert/ticks/index.json" with { type: "json" };
import AxisVertTicksLabelsJson from "./axis/vert/ticks/labels.json" with { type: "json" };
import AxisVertTitleJson from "./axis/vert/title.json" with { type: "json" };
import ChartJson from "./chart/index.json" with { type: "json" };
import ChartSubtitleJson from "./chart/subtitle.json" with { type: "json" };
import ChartTitleJson from "./chart/title.json" with { type: "json" };
import ColorJson from "./color.json" with { type: "json" };
import ControlpanelJson from "./controlPanel/index.json" with { type: "json" };
import ControlpanelCaptionJson from "./controlPanel/caption.json" with { type: "json" };
import DescriptionJson from "./description.json" with { type: "json" };
import GridJson from "./grid.json" with { type: "json" };
import LegendJson from "./legend/index.json" with { type: "json" };
import LegendBoxstyleJson from "./legend/boxStyle.json" with { type: "json" };
import MarkerJson from "./marker.json" with { type: "json" };
import PopupJson from "./popup.json" with { type: "json" };
import ScrollytellingJson from "./scrollytelling.json" with { type: "json" };
import SonificationJson from "./sonification.json" with { type: "json" };
import TypeJson from "./type/index.json" with { type: "json" };
import TypeBarJson from "./type/bar.json" with { type: "json" };
import TypeBubbleJson from "./type/bubble.json" with { type: "json" };
import TypeColumnJson from "./type/column.json" with { type: "json" };
import TypeComboJson from "./type/combo.json" with { type: "json" };
import TypeDonutJson from "./type/donut/index.json" with { type: "json" };
import TypeDonutInsidelabelsJson from "./type/donut/insideLabels.json" with { type: "json" };
import TypeDonutOutsidelabelsJson from "./type/donut/outsideLabels.json" with { type: "json" };
import TypeHeatmapJson from "./type/heatmap.json" with { type: "json" };
import TypeHistogramJson from "./type/histogram.json" with { type: "json" };
import TypeLineJson from "./type/line.json" with { type: "json" };
import TypePastryJson from "./type/pastry/index.json" with { type: "json" };
import TypePastryInsidelabelsJson from "./type/pastry/insideLabels.json" with { type: "json" };
import TypePastryOutsidelabelsJson from "./type/pastry/outsideLabels.json" with { type: "json" };
import TypePieJson from "./type/pie/index.json" with { type: "json" };
import TypePieInsidelabelsJson from "./type/pie/insideLabels.json" with { type: "json" };
import TypePieOutsidelabelsJson from "./type/pie/outsideLabels.json" with { type: "json" };
import TypePlaneJson from "./type/plane.json" with { type: "json" };
import TypeScatterJson from "./type/scatter.json" with { type: "json" };
import TypeVennJson from "./type/venn/index.json" with { type: "json" };
import TypeVennInsidelabelsJson from "./type/venn/insideLabels.json" with { type: "json" };
import TypeVennOutsidelabelsJson from "./type/venn/outsideLabels.json" with { type: "json" };
import TypeWaterfallJson from "./type/waterfall.json" with { type: "json" };
import UiJson from "./ui.json" with { type: "json" };

import { type ConfigGroupMetadata, type ConfigMetadata } from './config_metadata_types';
export type * from './config_metadata_types';

export const configMetadata: ConfigMetadata = {
  'animation': AnimationJson as unknown as ConfigGroupMetadata,
  'axis': AxisJson as unknown as ConfigGroupMetadata,
  'axis.horiz': AxisHorizJson as unknown as ConfigGroupMetadata,
  'axis.horiz.line': AxisHorizLineJson as unknown as ConfigGroupMetadata,
  'axis.horiz.ticks': AxisHorizTicksJson as unknown as ConfigGroupMetadata,
  'axis.horiz.ticks.labels': AxisHorizTicksLabelsJson as unknown as ConfigGroupMetadata,
  'axis.horiz.title': AxisHorizTitleJson as unknown as ConfigGroupMetadata,
  'axis.vert': AxisVertJson as unknown as ConfigGroupMetadata,
  'axis.vert.line': AxisVertLineJson as unknown as ConfigGroupMetadata,
  'axis.vert.ticks': AxisVertTicksJson as unknown as ConfigGroupMetadata,
  'axis.vert.ticks.labels': AxisVertTicksLabelsJson as unknown as ConfigGroupMetadata,
  'axis.vert.title': AxisVertTitleJson as unknown as ConfigGroupMetadata,
  'chart': ChartJson as unknown as ConfigGroupMetadata,
  'chart.subtitle': ChartSubtitleJson as unknown as ConfigGroupMetadata,
  'chart.title': ChartTitleJson as unknown as ConfigGroupMetadata,
  'color': ColorJson as unknown as ConfigGroupMetadata,
  'controlPanel': ControlpanelJson as unknown as ConfigGroupMetadata,
  'controlPanel.caption': ControlpanelCaptionJson as unknown as ConfigGroupMetadata,
  'description': DescriptionJson as unknown as ConfigGroupMetadata,
  'grid': GridJson as unknown as ConfigGroupMetadata,
  'legend': LegendJson as unknown as ConfigGroupMetadata,
  'legend.boxStyle': LegendBoxstyleJson as unknown as ConfigGroupMetadata,
  'marker': MarkerJson as unknown as ConfigGroupMetadata,
  'popup': PopupJson as unknown as ConfigGroupMetadata,
  'scrollytelling': ScrollytellingJson as unknown as ConfigGroupMetadata,
  'sonification': SonificationJson as unknown as ConfigGroupMetadata,
  'type': TypeJson as unknown as ConfigGroupMetadata,
  'type.bar': TypeBarJson as unknown as ConfigGroupMetadata,
  'type.bubble': TypeBubbleJson as unknown as ConfigGroupMetadata,
  'type.column': TypeColumnJson as unknown as ConfigGroupMetadata,
  'type.combo': TypeComboJson as unknown as ConfigGroupMetadata,
  'type.donut': TypeDonutJson as unknown as ConfigGroupMetadata,
  'type.donut.insideLabels': TypeDonutInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.donut.outsideLabels': TypeDonutOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.heatmap': TypeHeatmapJson as unknown as ConfigGroupMetadata,
  'type.histogram': TypeHistogramJson as unknown as ConfigGroupMetadata,
  'type.line': TypeLineJson as unknown as ConfigGroupMetadata,
  'type.pastry': TypePastryJson as unknown as ConfigGroupMetadata,
  'type.pastry.insideLabels': TypePastryInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pastry.outsideLabels': TypePastryOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pie': TypePieJson as unknown as ConfigGroupMetadata,
  'type.pie.insideLabels': TypePieInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pie.outsideLabels': TypePieOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.plane': TypePlaneJson as unknown as ConfigGroupMetadata,
  'type.scatter': TypeScatterJson as unknown as ConfigGroupMetadata,
  'type.venn': TypeVennJson as unknown as ConfigGroupMetadata,
  'type.venn.insideLabels': TypeVennInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.venn.outsideLabels': TypeVennOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.waterfall': TypeWaterfallJson as unknown as ConfigGroupMetadata,
  'ui': UiJson as unknown as ConfigGroupMetadata,
}

for (const [k, v] of Object.entries(configMetadata)) {
  if (!v) continue;
  if (v.ref) {
    const refTarget = configMetadata[v.ref];
    if (!refTarget) throw new Error(`Unknown config metadata ref: ${v.ref}`);
    const resolvedGroup = Object.assign(Object.create(refTarget), v) as ConfigGroupMetadata;
    resolvedGroup.settings = Object.assign(Object.create(refTarget.settings), v.settings);
    configMetadata[k] = resolvedGroup;
    for (const [sk, sv] of Object.entries(resolvedGroup.settings)) {
      const inheritedSetting = refTarget.settings[sk];
      if (inheritedSetting) {
        resolvedGroup.settings[sk] = Object.assign(Object.create(inheritedSetting), sv);
      }
    }
  }
}
