
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/

import ColorJson from "./color.json" with { type: "json" };
import ControlpanelJson from "./controlPanel/index.json" with { type: "json" };
import ControlpanelCaptionJson from "./controlPanel/caption.json" with { type: "json" };
import LegendJson from "./legend/index.json" with { type: "json" };
import LegendBoxstyleJson from "./legend/boxStyle.json" with { type: "json" };
import SonificationJson from "./sonification.json" with { type: "json" };
import ChartJson from "./chart/index.json" with { type: "json" };
import ChartSubtitleJson from "./chart/subtitle.json" with { type: "json" };
import ChartTitleJson from "./chart/title.json" with { type: "json" };
import DescriptionJson from "./description.json" with { type: "json" };
import UiJson from "./ui.json" with { type: "json" };
import TypeLineJson from "./type/line.json" with { type: "json" };
import TypePlaneJson from "./type/plane.json" with { type: "json" };
import TypeDonutJson from "./type/donut/index.json" with { type: "json" };
import TypeDonutOutsidelabelsJson from "./type/donut/outsideLabels.json" with { type: "json" };
import TypeDonutInsidelabelsJson from "./type/donut/insideLabels.json" with { type: "json" };
import TypePastryJson from "./type/pastry/index.json" with { type: "json" };
import TypePastryOutsidelabelsJson from "./type/pastry/outsideLabels.json" with { type: "json" };
import TypePastryInsidelabelsJson from "./type/pastry/insideLabels.json" with { type: "json" };
import TypeScatterJson from "./type/scatter.json" with { type: "json" };
import TypeColumnJson from "./type/column.json" with { type: "json" };
import TypePieJson from "./type/pie/index.json" with { type: "json" };
import TypePieOutsidelabelsJson from "./type/pie/outsideLabels.json" with { type: "json" };
import TypePieInsidelabelsJson from "./type/pie/insideLabels.json" with { type: "json" };
import TypeBarJson from "./type/bar.json" with { type: "json" };
import TypeWaterfallJson from "./type/waterfall.json" with { type: "json" };
import GridJson from "./grid.json" with { type: "json" };
import AxisVertJson from "./axis/vert/index.json" with { type: "json" };
import AxisVertLineJson from "./axis/vert/line.json" with { type: "json" };
import AxisVertTicksJson from "./axis/vert/ticks/index.json" with { type: "json" };
import AxisVertTicksLabelsJson from "./axis/vert/ticks/labels.json" with { type: "json" };
import AxisVertTitleJson from "./axis/vert/title.json" with { type: "json" };
import AxisHorizJson from "./axis/horiz/index.json" with { type: "json" };
import AxisHorizLineJson from "./axis/horiz/line.json" with { type: "json" };
import AxisHorizTicksJson from "./axis/horiz/ticks/index.json" with { type: "json" };
import AxisHorizTicksLabelsJson from "./axis/horiz/ticks/labels.json" with { type: "json" };
import AxisHorizTitleJson from "./axis/horiz/title.json" with { type: "json" };

import { SettingControlType } from '../components';
import { SettingControlOptionsType, RefreshTarget } from '../state';

export interface ConfigSettingMetadata<T extends SettingControlType = SettingControlType> {
  /** Label displayed in UI */
  label?: string;
  /** Internal description of item */
  description?: string;
  /** Stringified Typescript type of item */
  type?: string;
  default: any;
  control: T;
  /** Control-specific options. */
  controlOptions?: SettingControlOptionsType<T>;
  /** Whether item is advanced */
  advanced?: boolean;
  panel?: string;
  parentView?: string;
  hidden?: boolean;
  keywords?: string[];
  /** What to refresh when the setting changes **/
  refresh: RefreshTarget;
}
export interface ConfigGroupMetadata {
  ref?: string;
  settings: ConfigGroupSettingsMetadata;
}
export interface ConfigGroupSettingsMetadata {
  [settingName: string]: ConfigSettingMetadata;
}
export interface ConfigMetadata {
  [groupPath: string]: ConfigGroupMetadata;
}

export const configMetadata: ConfigMetadata = {
  'color': ColorJson as unknown as ConfigGroupMetadata,
  'controlPanel': ControlpanelJson as unknown as ConfigGroupMetadata,
  'controlPanel.caption': ControlpanelCaptionJson as unknown as ConfigGroupMetadata,
  'legend': LegendJson as unknown as ConfigGroupMetadata,
  'legend.boxStyle': LegendBoxstyleJson as unknown as ConfigGroupMetadata,
  'sonification': SonificationJson as unknown as ConfigGroupMetadata,
  'chart': ChartJson as unknown as ConfigGroupMetadata,
  'chart.subtitle': ChartSubtitleJson as unknown as ConfigGroupMetadata,
  'chart.title': ChartTitleJson as unknown as ConfigGroupMetadata,
  'description': DescriptionJson as unknown as ConfigGroupMetadata,
  'ui': UiJson as unknown as ConfigGroupMetadata,
  'type.line': TypeLineJson as unknown as ConfigGroupMetadata,
  'type.plane': TypePlaneJson as unknown as ConfigGroupMetadata,
  'type.donut': TypeDonutJson as unknown as ConfigGroupMetadata,
  'type.donut.outsideLabels': TypeDonutOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.donut.insideLabels': TypeDonutInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pastry': TypePastryJson as unknown as ConfigGroupMetadata,
  'type.pastry.outsideLabels': TypePastryOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pastry.insideLabels': TypePastryInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.scatter': TypeScatterJson as unknown as ConfigGroupMetadata,
  'type.column': TypeColumnJson as unknown as ConfigGroupMetadata,
  'type.pie': TypePieJson as unknown as ConfigGroupMetadata,
  'type.pie.outsideLabels': TypePieOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pie.insideLabels': TypePieInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.bar': TypeBarJson as unknown as ConfigGroupMetadata,
  'type.waterfall': TypeWaterfallJson as unknown as ConfigGroupMetadata,
  'grid': GridJson as unknown as ConfigGroupMetadata,
  'axis.vert': AxisVertJson as unknown as ConfigGroupMetadata,
  'axis.vert.line': AxisVertLineJson as unknown as ConfigGroupMetadata,
  'axis.vert.ticks': AxisVertTicksJson as unknown as ConfigGroupMetadata,
  'axis.vert.ticks.labels': AxisVertTicksLabelsJson as unknown as ConfigGroupMetadata,
  'axis.vert.title': AxisVertTitleJson as unknown as ConfigGroupMetadata,
  'axis.horiz': AxisHorizJson as unknown as ConfigGroupMetadata,
  'axis.horiz.line': AxisHorizLineJson as unknown as ConfigGroupMetadata,
  'axis.horiz.ticks': AxisHorizTicksJson as unknown as ConfigGroupMetadata,
  'axis.horiz.ticks.labels': AxisHorizTicksLabelsJson as unknown as ConfigGroupMetadata,
  'axis.horiz.title': AxisHorizTitleJson as unknown as ConfigGroupMetadata,
}

for (const [k, v] of Object.entries(configMetadata)) {
  if (v.ref) {
    const refTarget = configMetadata[v.ref];
    configMetadata[k] = Object.create(refTarget);
    Object.assign(configMetadata[k], v);
    configMetadata[k].settings = Object.create(refTarget.settings);
    Object.assign(configMetadata[k].settings, v.settings);
    for (const [sk, sv] of Object.entries(configMetadata[k].settings!)) {
      if (refTarget.settings![sk]) {
        configMetadata[k].settings![sk] = Object.create(refTarget.settings![sk]);
        Object.assign(configMetadata[k].settings![sk], sv);
      }
    }
  }
}

