
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/


/**
 * A single config item.
 * @public
 */
export type ConfigSetting = string | number | boolean;
/**
 * A group of config settings (which may contain nested config groups).
 * @public
 */
export type ConfigGroup = {[key: string]: ConfigSetting | ConfigGroup | undefined};


export interface Config extends ConfigGroup {
  color: ColorConfig;
  sonification: SonificationConfig;
  description: DescriptionConfig;
  ui: UiConfig;
  type: TypeConfig;
  axis: AxisConfig;
}
export interface ColorConfig extends ConfigGroup {
  /** Color vision deficiency simulation mode */
  colorVisionMode: 'normal' | 'deutan' | 'protan' | 'tritan' | 'grayscale';
  /** Enable dark color scheme */
  isDarkModeEnabled: boolean;
  /** Contrast adjustment level (0-2) */
  contrastLevel: number;
  /** Name of the color palette to use */
  colorPalette: string;
  /** Comma-separated list of custom color names */
  colorMap: string;
}
export interface SonificationConfig extends ConfigGroup {
  /** Enable sonification audio feedback */
  isSonificationEnabled: boolean;
  /** Enable series riff playback */
  isRiffEnabled: boolean;
  /** Enable audio notifications */
  isNotificationEnabled: boolean;
  /** Lower frequency bound in Hz */
  hertzLower: number;
  /** Upper frequency bound in Hz */
  hertzUpper: number;
  /** Speed for musical riffs */
  riffSpeedIndex: number;
  /** Play chords as arpeggios */
  isArpeggiateChords: boolean;
}
export interface DescriptionConfig extends ConfigGroup {
  /** Use concise or full captions */
  captionFormat: 'full' | 'concise';
}
export interface UiConfig extends ConfigGroup {
  /** Enable voice output for screen reader users */
  isVoicingEnabled: boolean;
  /** Enable visual highlighting when narrative elements are announced */
  isTourGuideEnabled: boolean;
  /** Pause Tour Guide temporarily */
  isTourGuidePaused: boolean;
  /** Enable aria-live announcements */
  isAnnouncementEnabled: boolean;
  /** Voice output speech rate. Range: 0.5 to 2 */
  speechRate: number;
  /** Enable fullscreen mode */
  isFullscreenEnabled: boolean;
  /** Enable low vision accessibility enhancements */
  isLowVisionModeEnabled: boolean;
  /** Show focus ring around active elements */
  isFocusRingEnabled: boolean;
  /** Gap size around focus ring in pixels */
  focusRingGap: number;
  /** Timeout in milliseconds for navigation runs */
  navRunTimeoutMs: number;
}
export interface TypeConfig extends ConfigGroup {
  donut: TypeDonutConfig;
  pie: TypePieConfig;
}
export interface TypeDonutConfig extends TypePastryConfig {
}
export interface TypePastryConfig extends ConfigGroup {
  /** Thickness of donut/gauge ring */
  annularThickness: number;
  /** What to show in center label */
  centerLabel: 'none' | 'title';
  /** Padding around center label */
  centerLabelPadding: number;
  /** Rotation offset for slice orientation */
  orientationAngleOffset: number;
  /** Which slices to separate from chart */
  explode: string;
  /** Distance for exploded slices */
  explodeDistance: number;
  outsideLabels: TypePastryOutsidelabelsConfig;
  insideLabels: TypePastryInsidelabelsConfig;
}
export interface TypePastryOutsidelabelsConfig extends ConfigGroup {
  /** Vertical gap between labels */
  vertGap: number;
  /** Gap between arc and label */
  arcGap: number;
  /** Horizontal shift for label positioning */
  horizShift: number;
  /** Horizontal padding around labels */
  horizPadding: number;
  /** Style of leader line to label */
  leaderStyle: 'direct' | 'underline';
  /** Label value format */
  format: string;
  /** Gap for underline leader style */
  underlineGap: number;
  /** Label content template */
  contents: string;
}
export interface TypePastryInsidelabelsConfig extends ConfigGroup {
  /** Label value format */
  format: string;
  /** Position as percentage of distance along radius */
  position: number;
  /** Label content template */
  contents: string;
}
export interface TypePieConfig extends TypePastryConfig {
}
export interface AxisConfig extends ConfigGroup {
  vert: AxisVertConfig;
}
export interface AxisVertConfig extends ConfigGroup {
}
