
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/

import ColorJson from "./color.json" with { type: "json" };
import SonificationJson from "./sonification.json" with { type: "json" };
import DescriptionJson from "./description.json" with { type: "json" };
import UiJson from "./ui.json" with { type: "json" };
import TypeDonutJson from "./type/donut/index.json" with { type: "json" };
import TypeDonutOutsidelabelsJson from "./type/donut/outsideLabels.json" with { type: "json" };
import TypeDonutInsidelabelsJson from "./type/donut/insideLabels.json" with { type: "json" };
import TypePastryJson from "./type/pastry/index.json" with { type: "json" };
import TypePastryOutsidelabelsJson from "./type/pastry/outsideLabels.json" with { type: "json" };
import TypePastryInsidelabelsJson from "./type/pastry/insideLabels.json" with { type: "json" };
import TypePieJson from "./type/pie/index.json" with { type: "json" };
import TypePieOutsidelabelsJson from "./type/pie/outsideLabels.json" with { type: "json" };
import TypePieInsidelabelsJson from "./type/pie/insideLabels.json" with { type: "json" };

import { SettingControlType } from '../components';
import { SettingControlOptionsType, RefreshTarget } from '../state';

export interface ConfigSettingMetadata<T extends SettingControlType = SettingControlType> {
  /** Label displayed in UI */
  label?: string;
  /** Internal description of item */
  description?: string;
  /** Stringified Typescript type of item */
  type?: string;
  default: any;
  control: T;
  /** Control-specific options. */
  controlOptions?: SettingControlOptionsType<T>;
  /** Whether item is advanced */
  advanced?: boolean;
  panel?: string;
  parentView?: string;
  hidden?: boolean;
  keywords?: string[];
  /** What to refresh when the setting changes **/
  refresh: RefreshTarget;
}
export interface ConfigGroupMetadata {
  ref?: string;
  settings: ConfigGroupSettingsMetadata;
}
export interface ConfigGroupSettingsMetadata {
  [settingName: string]: ConfigSettingMetadata;
}
export interface ConfigMetadata {
  [groupPath: string]: ConfigGroupMetadata;
}

export const configMetadata: ConfigMetadata = {
  'color': ColorJson as unknown as ConfigGroupMetadata,
  'sonification': SonificationJson as unknown as ConfigGroupMetadata,
  'description': DescriptionJson as unknown as ConfigGroupMetadata,
  'ui': UiJson as unknown as ConfigGroupMetadata,
  'type.donut': TypeDonutJson as unknown as ConfigGroupMetadata,
  'type.donut.outsideLabels': TypeDonutOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.donut.insideLabels': TypeDonutInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pastry': TypePastryJson as unknown as ConfigGroupMetadata,
  'type.pastry.outsideLabels': TypePastryOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pastry.insideLabels': TypePastryInsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pie': TypePieJson as unknown as ConfigGroupMetadata,
  'type.pie.outsideLabels': TypePieOutsidelabelsJson as unknown as ConfigGroupMetadata,
  'type.pie.insideLabels': TypePieInsidelabelsJson as unknown as ConfigGroupMetadata,
}

for (const [k, v] of Object.entries(configMetadata)) {
  if (v.ref) {
    const refTarget = configMetadata[v.ref];
    configMetadata[k] = Object.create(refTarget);
    Object.assign(configMetadata[k], v);
    configMetadata[k].settings = Object.create(refTarget.settings);
    Object.assign(configMetadata[k].settings, v.settings);
    for (const [sk, sv] of Object.entries(configMetadata[k].settings!)) {
      configMetadata[k].settings![sk] = Object.create(refTarget.settings![sk]);
      Object.assign(configMetadata[k].settings![sk], sv);
    }
  }
}

