
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/


import { type Size2d } from '@fizz/chart-classifier-utils'
import { type SnapLocation } from '../common/types';

/**
 * A single config item.
 * @public
 */
export type ConfigSetting = string | number | boolean;
/**
 * A group of config settings (which may contain nested config groups).
 * @public
 */
export type ConfigGroup = {[key: string]: ConfigSetting | ConfigGroup | undefined};

/** Chart types that display individual points
 * @public
 */
export type PointChartType = 'line' | 'stepline' | 'scatter';

/** Chart types drawn using a Cartesian coordinate system
 * @public
 */
export type PlaneChartType = 'bar' | 'lollipop' | PointChartType;

/** Chart types that use radial/circular layout
 * @public
 */
export type PastryChartType = 'pie' | 'donut' | 'gauge';

/** All supported chart types
 * @public
 */
export type ChartType = PlaneChartType | PastryChartType;

/** @public */
export type VertDirection = 'up' | 'down';

/** @public */
export type HorizDirection = 'left' | 'right';

/** @public */
export type PlaneDirection = VertDirection | HorizDirection;

/** @public */
export type DepthDirection = 'in' | 'out';

/** @public */
export type Direction = VertDirection | HorizDirection | DepthDirection;

/** @public */
export const directions: Direction[] = ['up', 'down', 'left', 'right', 'in', 'out'];

/** @public */
export type VertCardinalDirection = 'north' | 'south';
/** @public */
export type HorizCardinalDirection = 'east' | 'west';

/**
 * Which direction is "up" on a chart.
 * @public
 */
export type CardinalDirection = VertCardinalDirection | HorizCardinalDirection;


export interface Config extends ConfigGroup {
  color: ColorConfig;
  sonification: SonificationConfig;
  chart: ChartConfig;
  description: DescriptionConfig;
  ui: UiConfig;
  type: TypeConfig;
  grid: GridConfig;
  axis: AxisConfig;
}
export interface ColorConfig extends ConfigGroup {
  /** Color vision deficiency simulation mode */
  colorVisionMode: 'normal' | 'deutan' | 'protan' | 'tritan' | 'grayscale';
  /** Enable dark color scheme */
  isDarkModeEnabled: boolean;
  /** Contrast adjustment level (0-2) */
  contrastLevel: number;
  /** Name of the color palette to use */
  colorPalette: string;
  /** Comma-separated list of custom color names */
  colorMap: string;
}
export interface SonificationConfig extends ConfigGroup {
  /** Enable sonification audio feedback */
  isSonificationEnabled: boolean;
  /** Enable series riff playback */
  isRiffEnabled: boolean;
  /** Enable audio notifications */
  isNotificationEnabled: boolean;
  /** Lower frequency bound in Hz */
  hertzLower: number;
  /** Upper frequency bound in Hz */
  hertzUpper: number;
  /** Speed for musical riffs */
  riffSpeedIndex: number;
  /** Play chords as arpeggios */
  isArpeggiateChords: boolean;
}
export interface ChartConfig extends ConfigGroup {
  /** The type of chart to display */
  type: ChartType;
  /** Chart width in pixels */
  width: number;
  /** Chart height in pixels */
  height: number;
  /** Which direction is 'up' on the chart */
  orientation: CardinalDirection;
  /** Padding around chart content (CSS format) */
  padding: string;
  /** Font family for all chart text */
  fontFamily: string;
  /** Font weight for chart text */
  fontWeight: string;
  /** Global font size multiplier */
  fontScale: number;
  /** Stroke color for lines and shapes */
  stroke: string;
  /** Stroke width in pixels */
  strokeWidth: number;
  /** Scale factor for highlighted strokes */
  strokeHighlightScale: number;
  /** Stroke width for symbols in pixels */
  symbolStrokeWidth: number;
  /** Scale factor for highlighted symbols */
  symbolHighlightScale: number;
  /** Show direct labels on data points */
  hasDirectLabels: boolean;
  /** Font size for direct labels */
  directLabelFontSize: string;
  /** Show legend when direct labels are present */
  hasLegendWithDirectLabels: boolean;
  /** Draw symbols at data points */
  isDrawSymbols: boolean;
  /** Disable all interactivity */
  isStatic: boolean;
  /** Only show data points that have been visited */
  isShowVisitedDatapointsOnly: boolean;
  /** Show popups on hover or focus */
  isShowPopups: boolean;
  /** Max allowable error in first pass of segmentation algorithm */
  maxError: number;
  /** Max allowable segments in second pass of segmentation algorithm */
  maxSegments: number;
  /** Additional weight given to "peaks and valleys" during segmentation */
  extremumWeight: number;
  title: ChartTitleConfig;
}
export interface ChartTitleConfig extends ConfigGroup {
  /** Whether to draw the chart title */
  isDrawTitle: boolean;
  /** The text of the chart's title. */
  text: string;
  /** Space between the chart title and content (in SVG units). */
  margin: number;
  /** The font size of the chart title, as a CSS font size string. */
  fontSize: string;
  /** None */
  align: SnapLocation;
  /** The position of the chart title (either 'top' or 'bottom'). */
  position: 'top' | 'bottom';
}
export interface DescriptionConfig extends ConfigGroup {
  /** Use concise or full captions */
  captionFormat: 'full' | 'concise';
}
export interface UiConfig extends ConfigGroup {
  /** Enable voice output for screen reader users */
  isVoicingEnabled: boolean;
  /** Enable visual highlighting when narrative elements are announced */
  isTourGuideEnabled: boolean;
  /** Pause Tour Guide temporarily */
  isTourGuidePaused: boolean;
  /** Enable aria-live announcements */
  isAnnouncementEnabled: boolean;
  /** Voice output speech rate. Range: 0.5 to 2 */
  speechRate: number;
  /** Enable fullscreen mode */
  isFullscreenEnabled: boolean;
  /** Enable low vision accessibility enhancements */
  isLowVisionModeEnabled: boolean;
  /** Show focus ring around active elements */
  isFocusRingEnabled: boolean;
  /** Gap size around focus ring in pixels */
  focusRingGap: number;
  /** Timeout in milliseconds for navigation runs */
  navRunTimeoutMs: number;
}
export interface TypeConfig extends ConfigGroup {
  donut: TypeDonutConfig;
  pie: TypePieConfig;
}
export interface TypeDonutConfig extends TypePastryConfig {
}
export interface TypePastryConfig extends ConfigGroup {
  /** Thickness of donut/gauge ring */
  annularThickness: number;
  /** What to show in center label */
  centerLabel: 'none' | 'title';
  /** Padding around center label */
  centerLabelPadding: number;
  /** Rotation offset for slice orientation */
  orientationAngleOffset: number;
  /** Which slices to separate from chart */
  explode: string;
  /** Distance for exploded slices */
  explodeDistance: number;
  outsideLabels: TypePastryOutsidelabelsConfig;
  insideLabels: TypePastryInsidelabelsConfig;
}
export interface TypePastryOutsidelabelsConfig extends ConfigGroup {
  /** Vertical gap between labels */
  vertGap: number;
  /** Gap between arc and label */
  arcGap: number;
  /** Horizontal shift for label positioning */
  horizShift: number;
  /** Horizontal padding around labels */
  horizPadding: number;
  /** Style of leader line to label */
  leaderStyle: 'direct' | 'underline';
  /** Label value format */
  format: string;
  /** Gap for underline leader style */
  underlineGap: number;
  /** Label content template */
  contents: string;
}
export interface TypePastryInsidelabelsConfig extends ConfigGroup {
  /** Label value format */
  format: string;
  /** Position as percentage of distance along radius */
  position: number;
  /** Label content template */
  contents: string;
}
export interface TypePieConfig extends TypePastryConfig {
}
export interface GridConfig extends ConfigGroup {
  /** Draw horizontal grid lines */
  isDrawHorizLines: boolean;
  /** Draw vertical grid lines */
  isDrawVertLines: boolean;
  /** Draw line opposite horizontal axis */
  isDrawHorizAxisOppositeLine: boolean;
  /** Draw line opposite vertical axis */
  isDrawVertAxisOppositeLine: boolean;
}
export interface AxisConfig extends ConfigGroup {
  vert: AxisVertConfig;
  horiz: AxisHorizConfig;
}
export interface AxisVertConfig extends ConfigGroup {
  /** Enable drawing this axis */
  isDrawAxis: boolean;
  /** Position relative to chart */
  position: HorizCardinalDirection;
  /** Order of label values along axis */
  labelOrder: 'southToNorth' | 'northToSouth';
  /** Stagger labels to prevent overlap */
  isStaggerLabels: boolean;
  /** Wrap long labels onto multiple lines */
  isWrapLabels: boolean;
  line: AxisVertLineConfig;
  ticks: AxisVertTicksConfig;
  title: AxisVertTitleConfig;
}
export interface AxisVertLineConfig extends ConfigGroup {
  /** Draw the main axis line */
  isDrawAxisLine: boolean;
  /** Draw overhang beyond data range */
  isDrawOverhang: boolean;
  /** Width of axis line stroke */
  strokeWidth: number;
  /** End cap style for axis line */
  strokeLinecap: string;
}
export interface AxisVertTicksConfig extends ConfigGroup {
  /** Enable drawing of tick marks */
  isDrawTicks: boolean;
  /** Padding around tick marks */
  padding: number;
  /** Opacity of tick marks (0-1) */
  opacity: number;
  /** Width of tick mark lines */
  strokeWidth: number;
  /** End cap style for tick lines */
  strokeLinecap: string;
  /** Length of tick marks in pixels */
  length: number;
  /** Format for tick labels */
  labelFormat: string;
  /** Interval between tick marks */
  step: number;
  /** Whether ticks align with data points (bar charts only) */
  isOnDatapoint: boolean;
  labels: AxisVertTicksLabelsConfig;
}
export interface AxisVertTicksLabelsConfig extends ConfigGroup {
  /** Draw labels on tick marks */
  isDrawTickLabels: boolean;
  /** Font size for tick labels */
  fontSize: string;
  /** Rotation angle for labels in degrees */
  angle: number;
  /** Offset distance from tick marks */
  offsetGap: number;
  /** Gap between adjacent labels */
  gap: number;
}
export interface AxisVertTitleConfig extends ConfigGroup {
  /** Draw axis title */
  isDrawTitle: boolean;
  /** Title text content */
  text: string;
  /** Gap between title and axis */
  gap: number;
  /** Font size for title */
  fontSize: string;
  /** Text alignment relative to axis */
  align: 'start' | 'middle' | 'end';
}
export interface AxisHorizConfig extends ConfigGroup {
  /** Enable drawing this axis */
  isDrawAxis: boolean;
  /** Position relative to chart */
  position: VertCardinalDirection;
  /** Order of label values along axis */
  labelOrder: 'westToEast' | 'eastToWest';
  /** Stagger labels to prevent overlap */
  isStaggerLabels: boolean;
  /** Wrap long labels to multiple lines */
  isWrapLabels: boolean;
  line: AxisHorizLineConfig;
  ticks: AxisHorizTicksConfig;
  title: AxisHorizTitleConfig;
}
export interface AxisHorizLineConfig extends ConfigGroup {
  /** Draw the main axis line */
  isDrawAxisLine: boolean;
  /** Draw overhang beyond data range */
  isDrawOverhang: boolean;
  /** Width of axis line stroke */
  strokeWidth: number;
  /** End cap style for axis line */
  strokeLinecap: string;
}
export interface AxisHorizTicksConfig extends ConfigGroup {
  /** Enable drawing of tick marks */
  isDrawTicks: boolean;
  /** Padding around tick marks */
  padding: number;
  /** Opacity of tick marks (0-1) */
  opacity: number;
  /** Width of tick mark lines */
  strokeWidth: number;
  /** End cap style for tick lines */
  strokeLinecap: string;
  /** Length of tick marks in pixels */
  length: number;
  /** Format for tick labels */
  labelFormat: string;
  /** Interval between tick marks */
  step: number;
  /** Whether ticks align with data points (bar charts only) */
  isOnDatapoint: boolean;
  labels: AxisHorizTicksLabelsConfig;
}
export interface AxisHorizTicksLabelsConfig extends ConfigGroup {
  /** Draw labels on tick marks */
  isDrawTickLabels: boolean;
  /** Font size for tick labels */
  fontSize: string;
  /** Rotation angle for labels in degrees */
  angle: number;
  /** Offset distance from tick marks */
  offsetGap: number;
  /** Gap between adjacent labels */
  gap: number;
}
export interface AxisHorizTitleConfig extends ConfigGroup {
  /** Draw axis title */
  isDrawTitle: boolean;
  /** Title text content */
  text: string;
  /** Gap between title and axis */
  gap: number;
  /** Font size for title */
  fontSize: string;
  /** Text alignment relative to axis */
  align: 'start' | 'middle' | 'end';
}
