
/*
DO NOT HAND-EDIT THIS FILE. It is generated by build_settings.py.
*/

import { Config } from './config_types';
export const defaultConfig: Config = {
    sonification: {
      isSonificationEnabled: false,
      isRiffEnabled: true,
      isNotificationEnabled: true,
      hertzLower: 35,
      hertzUpper: 96,
      riffSpeedIndex: 2,
      isArpeggiateChords: true,
    },
    ui: {
      isVoicingEnabled: false,
      isTourGuideEnabled: false,
      isTourGuidePaused: false,
      isAnnouncementEnabled: true,
      speechRate: 1,
      isFullscreenEnabled: false,
      isLowVisionModeEnabled: false,
      isFocusRingEnabled: false,
      focusRingGap: 10,
      navRunTimeoutMs: 125,
    },
    type: {
      donut: {
        outsideLabels: {
          vertGap: 10,
          arcGap: 10,
          horizShift: 15,
          horizPadding: 10,
          leaderStyle: "direct",
          format: "raw",
          underlineGap: 2,
          contents: "percentage:(value)",
        },
        annularThickness: 0.5,
        centerLabel: "title",
        centerLabelPadding: 15,
        orientationAngleOffset: 90,
        explode: "",
        explodeDistance: 20,
        insideLabels: {
          format: "raw",
          position: 0.85,
          contents: "category",
        },
      },
      pie: {
        outsideLabels: {
          vertGap: 10,
          arcGap: 10,
          horizShift: 15,
          horizPadding: 10,
          leaderStyle: "direct",
          format: "raw",
          underlineGap: 2,
          contents: "percentage:(value)",
        },
        annularThickness: 1,
        centerLabel: "none",
        centerLabelPadding: 10,
        orientationAngleOffset: 90,
        explode: "",
        explodeDistance: 20,
        insideLabels: {
          format: "raw",
          position: 0.9,
          contents: "category",
        },
      },
    },
}
